import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart' hide AuthProvider;
import 'package:intl/intl.dart';
import '../models/habit_model.dart';
import '../utils/ramadhan_utils.dart';
import 'auth_provider.dart';

class HabitProvider with ChangeNotifier {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  List<HabitModel> _habits = [];
  bool _isLoading = false;

  List<HabitModel> get habits => _habits;
  bool get isLoading => _isLoading;

  /// Ambil semua habit user
  Future<void> fetchHabits(AuthProvider authProvider) async {
    if (_isLoading) return;

    final user = _auth.currentUser;
    if (user == null) {
      _habits = [];
      notifyListeners();
      return;
    }

    _isLoading = true;
    notifyListeners();

    try {
      final snapshot = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('habits')
          .get();

      _habits = snapshot.docs
          .map((doc) => HabitModel.fromMap(doc.id, doc.data()))
          .toList();

      // Sort: Auto-generated di atas, sisanya terbaru di atas
      _habits.sort((a, b) {
        if (a.isAutoGenerated != b.isAutoGenerated) {
          return a.isAutoGenerated ? -1 : 1;
        }
        final dateA = a.createdAt ?? DateTime(2000);
        final dateB = b.createdAt ?? DateTime(2000);
        return dateB.compareTo(dateA);
      });

      // Sinkronisasi habit khatam otomatis dengan dailyJuzTarget yang dikunci
      if (authProvider.userData != null) {
        await syncKhatamHabit(
          authProvider.userData!.targetKhatam,
          authProvider.userData!.completedJuz,
          authProvider.ramadhanStartDate,
          authProvider.totalRamadhanDays,
          authProvider.userData!.dailyJuzTarget,
        );

        // Tambahkan habit default lainnya HANYA SEKALI jika belum pernah
        if (!authProvider.userData!.hasSetupDefaultHabits) {
          await _setupInitialDefaultHabits(authProvider);
        }
      }
    } catch (e) {
      debugPrint("Error fetching habits: $e");
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  /// Bersihkan data (panggil saat logout)
  void clearData() {
    _habits = [];
    _isLoading = false;
    notifyListeners();
  }

  /// Toggle status ceklis pada tanggal tertentu
  Future<void> toggleHabit(
      String habitId, DateTime date, AuthProvider authProvider) async {
    final user = _auth.currentUser;
    if (user == null) return;

    final dateKey = DateFormat('yyyy-MM-dd').format(date);
    final habitIndex = _habits.indexWhere((h) => h.id == habitId);

    if (habitIndex != -1) {
      final habit = _habits[habitIndex];
      final currentStatus = habit.completionStatus[dateKey] ?? false;

      // Update lokal dulu
      final newStatus = Map<String, bool>.from(habit.completionStatus);
      newStatus[dateKey] = !currentStatus;

      double deltaJuz = 0.0;
      Map<String, double> newJuzStatus =
          Map<String, double>.from(habit.juzCompletedPerDay);

      if (habit.isAutoGenerated) {
        if (!currentStatus) {
          // Gunakan target yang sudah dikunci (dailyJuzTarget)
          double dailyTarget = authProvider.userData?.dailyJuzTarget ?? 1.0;
          deltaJuz = dailyTarget;
          newJuzStatus[dateKey] = dailyTarget;
        } else {
          deltaJuz = -(habit.juzCompletedPerDay[dateKey] ?? 0.0);
          newJuzStatus.remove(dateKey);
        }
      }

      _habits[habitIndex] = habit.copyWith(
        completionStatus: newStatus,
        juzCompletedPerDay: newJuzStatus,
      );
      notifyListeners();

      try {
        final Map<String, dynamic> updates = {
          'completionStatus.$dateKey': !currentStatus,
        };

        if (habit.isAutoGenerated) {
          if (!currentStatus) {
            updates['juzCompletedPerDay.$dateKey'] = newJuzStatus[dateKey];
          } else {
            updates['juzCompletedPerDay.$dateKey'] = FieldValue.delete();
          }
          await authProvider.updateCompletedJuz(deltaJuz);
        }

        await _firestore
            .collection('users')
            .doc(user.uid)
            .collection('habits')
            .doc(habitId)
            .update(updates);

        // Setelah progres berubah, sinkronkan habit (nama tetap krn pakai dailyJuzTarget)
        if (habit.isAutoGenerated && authProvider.userData != null) {
          await syncKhatamHabit(
            authProvider.userData!.targetKhatam,
            authProvider.userData!.completedJuz,
            authProvider.ramadhanStartDate,
            authProvider.totalRamadhanDays,
            authProvider.userData!.dailyJuzTarget,
          );
        }
      } catch (e) {
        _habits[habitIndex] = habit;
        notifyListeners();
        rethrow;
      }
    }
  }

  /// Sinkronisasi habit Khatam otomatis
  Future<void> syncKhatamHabit(
    int targetKhatam,
    double completedJuz,
    DateTime ramadhanStartDate,
    int totalRamadhanDays, [
    double? lockedDailyTarget,
  ]) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      double dailyTarget;
      if (lockedDailyTarget != null) {
        dailyTarget = lockedDailyTarget;
      } else {
        dailyTarget = RamadhanUtils.calculateDailyTarget(
          totalTargetKhatam: targetKhatam,
          completedJuz: completedJuz,
          startDate: ramadhanStartDate,
          totalRamadhanDays: totalRamadhanDays,
        );
      }

      final habitName =
          "Baca Quran ${RamadhanUtils.formatJuzTarget(dailyTarget)}";

      // Cari habit khatam (yang isAutoGenerated dan namanya mengandung "Baca Quran")
      final khatamIndex = _habits.indexWhere(
          (h) => h.isAutoGenerated == true && h.name.contains("Baca Quran"));

      if (khatamIndex == -1) {
        final newKhatam = HabitModel(
          id: '',
          name: habitName,
          scheduledDays: [1, 2, 3, 4, 5, 6, 7],
          isAutoGenerated: true,
          createdAt: DateTime.now(),
        );

        final docRef = await _firestore
            .collection('users')
            .doc(user.uid)
            .collection('habits')
            .add(newKhatam.toMap());

        _habits.insert(0, newKhatam.copyWith(id: docRef.id));
        notifyListeners();
      } else {
        final existing = _habits[khatamIndex];
        if (existing.name != habitName) {
          await _firestore
              .collection('users')
              .doc(user.uid)
              .collection('habits')
              .doc(existing.id)
              .update({'name': habitName});

          _habits[khatamIndex] = existing.copyWith(name: habitName);
          notifyListeners();
        }
      }
    } catch (e) {
      debugPrint("Error syncing khatam habit: $e");
    }
  }

  /// Setup amalan default untuk pengguna baru (hanya jalan sekali)
  Future<void> _setupInitialDefaultHabits(AuthProvider authProvider) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      final defaultHabits = [
        "Shalat Duha 4 Rakaat",
        "Nonton Kajian Islami",
      ];

      for (String name in defaultHabits) {
        // Cek lagi apakah sudah ada secara manual (just in case)
        final alreadyExists = _habits.any((h) => h.name == name);
        if (alreadyExists) continue;

        final newHabit = HabitModel(
          id: '',
          name: name,
          scheduledDays: [1, 2, 3, 4, 5, 6, 7],
          isAutoGenerated: false, // Boleh di-edit/hapus oleh user
          createdAt: DateTime.now(),
        );

        final docRef = await _firestore
            .collection('users')
            .doc(user.uid)
            .collection('habits')
            .add(newHabit.toMap());

        _habits.add(newHabit.copyWith(id: docRef.id));
      }

      // Tandai sudah setup agar tidak dibuat lagi saat refresh/login ulang
      await authProvider.setHasSetupDefaultHabits(true);

      notifyListeners();
    } catch (e) {
      debugPrint("Error setting up initial habits: $e");
    }
  }

  /// Tambah habit baru (Custom)
  Future<void> addHabit(String name, List<int> days,
      {String type = 'harian', int? targetPerWeek}) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      final newHabit = HabitModel(
        id: '',
        name: name,
        scheduledDays: days,
        type: type,
        targetPerWeek: targetPerWeek,
        createdAt: DateTime.now(),
      );

      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('habits')
          .add(newHabit.toMap());
    } catch (e) {
      rethrow;
    }
  }

  /// Update habit
  Future<void> updateHabit(String habitId, String name, List<int> days,
      {String type = 'harian', int? targetPerWeek}) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('habits')
          .doc(habitId)
          .update({
        'name': name,
        'scheduledDays': days,
        'type': type,
        'targetPerWeek': targetPerWeek,
      });

      final index = _habits.indexWhere((h) => h.id == habitId);
      if (index != -1) {
        _habits[index] = _habits[index].copyWith(
          name: name,
          scheduledDays: days,
          type: type,
          targetPerWeek: targetPerWeek,
        );
        notifyListeners();
      }
    } catch (e) {
      rethrow;
    }
  }

  /// Hapus habit
  Future<void> deleteHabit(String habitId) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('habits')
          .doc(habitId)
          .delete();

      _habits.removeWhere((h) => h.id == habitId);
      notifyListeners();
    } catch (e) {
      rethrow;
    }
  }
}
