import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:intl/intl.dart';
import '../models/habit_model.dart';

class HabitProvider with ChangeNotifier {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  List<HabitModel> _habits = [];
  bool _isLoading = false;

  List<HabitModel> get habits => _habits;
  bool get isLoading => _isLoading;

  /// Ambil semua habit user
  Future<void> fetchHabits(int targetKhatam) async {
    final user = _auth.currentUser;
    if (user == null) return;

    _isLoading = true;
    notifyListeners();

    try {
      final snapshot = await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('habits')
          .get();

      _habits = snapshot.docs
          .map((doc) => HabitModel.fromMap(doc.id, doc.data()))
          .toList();

      // URUTAN: Auto-generated paling atas, sisanya terbaru di atas (yang pertama dibuat ke bawah terus)
      _habits.sort((a, b) {
        if (a.isAutoGenerated != b.isAutoGenerated) {
          return a.isAutoGenerated ? -1 : 1;
        }
        // Jika keduanya custom, urutkan berdasarkan createdAt (terbaru di atas)
        final dateA = a.createdAt ?? DateTime(2000);
        final dateB = b.createdAt ?? DateTime(2000);
        return dateB.compareTo(dateA);
      });

      // Sinkronisasi habit khatam otomatis
      await syncKhatamHabit(targetKhatam);
    } catch (e) {
      debugPrint("Error fetching habits: $e");
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  /// Tambah habit baru (Custom)
  Future<void> addHabit(String name, List<int> days,
      {String type = 'harian', int? targetPerWeek}) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      final newHabit = HabitModel(
        id: '', // Diisi Firestore
        name: name,
        scheduledDays: days,
        type: type,
        targetPerWeek: targetPerWeek,
        createdAt: DateTime.now(),
      );

      debugPrint("Mencoba simpan habit baru ke Firestore...");
      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('habits')
          .add(newHabit.toMap());
      debugPrint("Habit berhasil disimpan ke Firestore.");

      // Ambil detail user untuk mendapatkan targetKhatam yang benar
      final userDoc = await _firestore.collection('users').doc(user.uid).get();
      final targetKhatam = userDoc.data()?['targetKhatam'] ?? 1;

      debugPrint("Menyegarkan daftar habit...");
      await fetchHabits(targetKhatam);
      debugPrint("Penyegaran selesai.");
    } catch (e) {
      debugPrint("Error saat addHabit: $e");
      rethrow;
    }
  }

  /// Toggle status ceklis pada tanggal tertentu
  Future<void> toggleHabit(String habitId, DateTime date) async {
    final user = _auth.currentUser;
    if (user == null) return;

    final dateKey = DateFormat('yyyy-MM-dd').format(date);
    final habitIndex = _habits.indexWhere((h) => h.id == habitId);

    if (habitIndex != -1) {
      final habit = _habits[habitIndex];
      final currentStatus = habit.completionStatus[dateKey] ?? false;

      // Update lokal dulu biar responsif
      final newStatus = Map<String, bool>.from(habit.completionStatus);
      newStatus[dateKey] = !currentStatus;
      _habits[habitIndex] = habit.copyWith(completionStatus: newStatus);
      notifyListeners();

      try {
        await _firestore
            .collection('users')
            .doc(user.uid)
            .collection('habits')
            .doc(habitId)
            .update({'completionStatus.$dateKey': !currentStatus});
      } catch (e) {
        // Rollback jika gagal
        _habits[habitIndex] = habit;
        notifyListeners();
        rethrow;
      }
    }
  }

  /// Update habit yang sudah ada
  Future<void> updateHabit(String habitId, String name, List<int> days,
      {String type = 'harian', int? targetPerWeek}) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('habits')
          .doc(habitId)
          .update({
        'name': name,
        'scheduledDays': days,
        'type': type,
        'targetPerWeek': targetPerWeek,
      });

      // Update local state
      final index = _habits.indexWhere((h) => h.id == habitId);
      if (index != -1) {
        _habits[index] = _habits[index].copyWith(
          name: name,
          scheduledDays: days,
          type: type,
          targetPerWeek: targetPerWeek,
        );
        notifyListeners();
      }
    } catch (e) {
      debugPrint("Error updating habit: $e");
      rethrow;
    }
  }

  /// Hapus habit
  Future<void> deleteHabit(String habitId) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      await _firestore
          .collection('users')
          .doc(user.uid)
          .collection('habits')
          .doc(habitId)
          .delete();

      _habits.removeWhere((h) => h.id == habitId);
      notifyListeners();
    } catch (e) {
      debugPrint("Error deleting habit: $e");
      rethrow;
    }
  }

  /// Sinkronisasi habit Khatam otomatis berdasarkan target user
  Future<void> syncKhatamHabit(int targetKhatam) async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      final juzPerDay = targetKhatam; // Langsung gunakan integer
      final habitName = "Baca Quran $juzPerDay Juz";

      // Cari di lokal dulu
      final khatamIndex = _habits.indexWhere((h) => h.isAutoGenerated == true);

      if (khatamIndex == -1) {
        // Buat baru di Firestore
        final newKhatam = HabitModel(
          id: '',
          name: habitName,
          scheduledDays: [1, 2, 3, 4, 5, 6, 7],
          isAutoGenerated: true,
        );

        final docRef = await _firestore
            .collection('users')
            .doc(user.uid)
            .collection('habits')
            .add(newKhatam.toMap());

        // Tambahkan ke list lokal dengan ID asli di posisi paling atas setelah sort
        _habits.insert(
            0, newKhatam.copyWith(id: docRef.id, createdAt: DateTime.now()));
        notifyListeners();
      } else {
        // Update jika nama berbeda
        final existing = _habits[khatamIndex];
        if (existing.name != habitName) {
          await _firestore
              .collection('users')
              .doc(user.uid)
              .collection('habits')
              .doc(existing.id)
              .update({'name': habitName});

          _habits[khatamIndex] = existing.copyWith(name: habitName);
          notifyListeners();
        }
      }
    } catch (e) {
      debugPrint("Error syncing khatam habit: $e");
    }
  }
}
