import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:provider/provider.dart';
import '../../models/habit_model.dart';
import '../../providers/habit_provider.dart';
import 'create_habit_screen.dart';

/// HABIT DETAIL SCREEN
/// Halaman detail amalan yang menampilkan opsi edit dan hapus
class HabitDetailScreen extends StatelessWidget {
  final HabitModel habit;

  const HabitDetailScreen({
    super.key,
    required this.habit,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        toolbarHeight: 90,
        leading: Padding(
          padding: const EdgeInsets.only(top: 16),
          child: IconButton(
            icon: const Icon(Icons.arrow_back, color: Color(0xFF1A1A1A)),
            onPressed: () => Navigator.pop(context),
          ),
        ),
        title: const Padding(
          padding: EdgeInsets.only(top: 16),
          child: Text(
            'Detail Amalan',
            style: TextStyle(
              color: Color(0xFF1A1A1A),
              fontSize: 18,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 10),

              // Habit Header Info
              _buildHabitInfo(),

              const SizedBox(height: 40),

              // EDIT HABIT BUTTON
              if (!habit.isAutoGenerated) // Jangan edit habit otomatis
                _buildMenuButton(
                  context: context,
                  icon: Icons.edit_outlined,
                  label: 'Edit Amalan',
                  subtitle: 'Ubah nama atau jadwal amalan',
                  onTap: () async {
                    final result = await Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => CreateHabitScreen(habit: habit),
                      ),
                    );
                    if (result == true && context.mounted) {
                      Navigator.pop(
                          context, 'edit'); // Pass result back to HomeScreen
                    }
                  },
                ),

              const SizedBox(height: 12),

              // HAPUS HABIT BUTTON
              if (!habit.isAutoGenerated) // Jangan hapus habit otomatis
                _buildMenuButton(
                  context: context,
                  icon: Icons.delete_outline,
                  label: 'Hapus Amalan',
                  subtitle: 'Hapus amalan ini secara permanen',
                  isDestructive: true,
                  onTap: () => _showDeleteConfirmation(context),
                ),

              const Spacer(),

              // INFO BOX
              _buildInfoBox(),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildHabitInfo() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: const Color(0xFFF5F5F5),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Column(
        children: [
          const Text('📝', style: TextStyle(fontSize: 48)),
          const SizedBox(height: 16),
          Text(
            habit.name,
            textAlign: TextAlign.center,
            style: const TextStyle(
              fontSize: 22,
              fontWeight: FontWeight.bold,
              color: Color(0xFF1A1A1A),
            ),
          ),
          const SizedBox(height: 8),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decoration: BoxDecoration(
                  color: const Color(0xFFE8F9EC),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  habit.type == 'harian' ? 'Amalan Harian' : 'Amalan Mingguan',
                  style: const TextStyle(
                    color: Color(0xFF32D74B),
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            habit.type == 'harian'
                ? (habit.scheduledDays.length == 7
                    ? 'Setiap hari'
                    : () {
                        final daysList = habit.scheduledDays
                            .map((d) => [
                                  'Sen',
                                  'Sel',
                                  'Rab',
                                  'Kam',
                                  'Jum',
                                  'Sab',
                                  'Min'
                                ][d - 1])
                            .toList();
                        if (daysList.length == 1) return daysList.first;
                        final last = daysList.removeLast();
                        return '${daysList.join(', ')} dan $last';
                      }())
                : (habit.targetPerWeek == 7
                    ? 'Setiap hari'
                    : '${habit.targetPerWeek} kali seminggu'),
            style: TextStyle(
              fontSize: 14,
              color: Colors.grey[600],
              fontWeight: FontWeight.w500,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildMenuButton({
    required BuildContext context,
    required IconData icon,
    required String label,
    required String subtitle,
    required VoidCallback onTap,
    bool isDestructive = false,
  }) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(16),
      child: Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color:
              isDestructive ? const Color(0xFFFFF3F3) : const Color(0xFFF5F5F5),
          borderRadius: BorderRadius.circular(16),
        ),
        child: Row(
          children: [
            Container(
              width: 48,
              height: 48,
              decoration: BoxDecoration(
                color: isDestructive
                    ? const Color(0xFFFF3B30).withOpacity(0.1)
                    : Colors.white,
                borderRadius: BorderRadius.circular(12),
              ),
              child: Icon(icon,
                  color: isDestructive
                      ? const Color(0xFFFF3B30)
                      : const Color(0xFF32D74B),
                  size: 24),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(label,
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                        color: isDestructive
                            ? const Color(0xFFFF3B30)
                            : const Color(0xFF1A1A1A),
                      )),
                  const SizedBox(height: 4),
                  Text(subtitle,
                      style: TextStyle(fontSize: 13, color: Colors.grey[600])),
                ],
              ),
            ),
            Icon(Icons.arrow_forward_ios,
                size: 14,
                color:
                    isDestructive ? const Color(0xFFFF3B30) : Colors.grey[400]),
          ],
        ),
      ),
    );
  }

  Widget _buildInfoBox() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
          color: const Color(0xFFE8F9EC),
          borderRadius: BorderRadius.circular(16)),
      child: Row(
        children: [
          const Icon(Icons.lightbulb_outline, color: Color(0xFF32D74B)),
          const SizedBox(width: 12),
          const Expanded(
            child: Text(
              'Tips: Kamu bisa mengubah jadwal atau menghapus amalan ini kapan saja.',
              style: TextStyle(
                  fontSize: 13, color: Color(0xFF32D74B), height: 1.4),
            ),
          ),
        ],
      ),
    );
  }

  void _showDeleteConfirmation(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Text('Hapus Amalan?'),
        content: Text('Apakah kamu yakin ingin menghapus "${habit.name}"?'),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Batal', style: TextStyle(color: Colors.grey))),
          TextButton(
            onPressed: () async {
              try {
                await context.read<HabitProvider>().deleteHabit(habit.id);
                if (context.mounted) {
                  Navigator.pop(context); // Close dialog
                  Navigator.pop(context, 'delete'); // Signal to HomeScreen
                }
              } catch (e) {
                Fluttertoast.showToast(msg: "Gagal menghapus: $e");
              }
            },
            child: const Text('Hapus',
                style: TextStyle(
                    color: Color(0xFFFF3B30), fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );
  }
}
