import 'package:cloud_firestore/cloud_firestore.dart';

class HabitModel {
  final String id;
  final String name;
  final List<int> scheduledDays; // [1, 2, 3, 4, 5, 6, 7] (1=Senin, 7=Minggu)
  final Map<String, bool> completionStatus; // {"2026-02-11": true}
  final bool isAutoGenerated;
  final String? type; // 'harian', 'mingguan'
  final int? targetPerWeek;
  final Map<String, double> juzCompletedPerDay; // {"2026-02-11": 1.0}
  final DateTime? createdAt;

  HabitModel({
    required this.id,
    required this.name,
    required this.scheduledDays,
    this.completionStatus = const {},
    this.isAutoGenerated = false,
    this.type = 'harian',
    this.targetPerWeek,
    this.juzCompletedPerDay = const {},
    this.createdAt,
  });

  factory HabitModel.fromMap(String id, Map<String, dynamic> map) {
    return HabitModel(
      id: id,
      name: map['name'] ?? '',
      scheduledDays: List<int>.from(map['scheduledDays'] ?? []),
      completionStatus: Map<String, bool>.from(map['completionStatus'] ?? {}),
      isAutoGenerated: map['isAutoGenerated'] ?? false,
      type: map['type'] ?? 'harian',
      targetPerWeek: map['targetPerWeek'],
      juzCompletedPerDay: Map<String, double>.from(
          (map['juzCompletedPerDay'] ?? {})
              .map((key, value) => MapEntry(key, (value ?? 0.0).toDouble()))),
      createdAt: map['createdAt'] != null
          ? (map['createdAt'] as Timestamp).toDate()
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'scheduledDays': scheduledDays,
      'completionStatus': completionStatus,
      'isAutoGenerated': isAutoGenerated,
      'type': type,
      'targetPerWeek': targetPerWeek,
      'juzCompletedPerDay': juzCompletedPerDay,
      'createdAt': createdAt != null ? Timestamp.fromDate(createdAt!) : null,
    };
  }

  HabitModel copyWith({
    String? id,
    String? name,
    List<int>? scheduledDays,
    Map<String, bool>? completionStatus,
    String? type,
    int? targetPerWeek,
    Map<String, double>? juzCompletedPerDay,
    DateTime? createdAt,
  }) {
    return HabitModel(
      id: id ?? this.id,
      name: name ?? this.name,
      scheduledDays: scheduledDays ?? this.scheduledDays,
      completionStatus: completionStatus ?? this.completionStatus,
      isAutoGenerated: isAutoGenerated,
      type: type ?? this.type,
      targetPerWeek: targetPerWeek ?? this.targetPerWeek,
      juzCompletedPerDay: juzCompletedPerDay ?? this.juzCompletedPerDay,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
